# Generated by Django 4.2.2 on 2023-06-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_autor_genre_publishing_house_series_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='book',
            name='active',
            field=models.CharField(choices=[('Y', 'active'), ('N', 'inactive')], max_length=4),
        ),
        migrations.AlterField(
            model_name='book',
            name='binding',
            field=models.CharField(choices=[('Solid', 'solid'), ('Soft', 'soft'), ('Absent', 'absent')], max_length=6),
        ),
        migrations.AlterField(
            model_name='book',
            name='format_book',
            field=models.CharField(choices=[('Super small', '84x108/64'), ('Small', '75x90/32'), ('Standart', '60x90/16'), ('Bigger', '70x108/16'), ('Big', '60x90/8'), ('Super big', '84x108/8')], max_length=12),
        ),
    ]
