# Generated by Django 4.2.2 on 2023-07-04 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='Author name')),
                ('author_description', models.TextField(blank=True, null=True, verbose_name='Author description')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=50, verbose_name='Genre')),
                ('genre_description', models.TextField(blank=True, null=True, verbose_name='Genre description')),
            ],
        ),
        migrations.CreateModel(
            name='Publishing_House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing_house_name', models.CharField(max_length=50, verbose_name='Publishing house name')),
                ('publishing_house_description', models.TextField(blank=True, null=True, verbose_name='Publishing house description')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=100, verbose_name='Series')),
                ('series_description', models.TextField(blank=True, null=True, verbose_name="Count book's series")),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=150)),
                ('book_image', models.ImageField(blank=True, upload_to='book/%Y/%m/%d/')),
                ('book_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('year_publishing', models.DateField(max_length=50)),
                ('page', models.DecimalField(decimal_places=0, default=0, max_digits=6)),
                ('binding', models.CharField(choices=[('Solid', 'solid'), ('Soft', 'soft'), ('Absent', 'absent')], max_length=6)),
                ('format_book', models.CharField(choices=[('Super small', '84x108/64'), ('Small', '75x90/32'), ('Standart', '60x90/16'), ('Bigger', '70x108/16'), ('Big', '60x90/8'), ('Super big', '84x108/8')], max_length=12)),
                ('ISBN', models.CharField(max_length=25)),
                ('weight', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('age_restrictions', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('counter_book', models.DecimalField(decimal_places=0, default=0, max_digits=7)),
                ('active', models.CharField(choices=[('Y', 'active'), ('N', 'inactive')], max_length=4)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshop.author')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshop.genre')),
                ('publishing_house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookshop.publishing_house')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookshop.series')),
            ],
        ),
    ]
