# Generated by Django 4.2.2 on 2023-07-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=255, verbose_name='Genre name')),
                ('genre_description', models.TextField(blank=True, null=True, verbose_name='Genre description')),
            ],
        ),
    ]
