# Generated by Django 4.2.2 on 2023-07-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0002_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=255, verbose_name='Series count')),
                ('series_description', models.TextField(blank=True, null=True, verbose_name='Series information')),
            ],
        ),
    ]
