# Generated by Django 4.2.2 on 2023-07-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0003_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing_name', models.CharField(max_length=255, verbose_name='Publishing name')),
                ('publishing_description', models.TextField(blank=True, null=True, verbose_name='Publishing information')),
            ],
        ),
    ]
